### ISSUE TITLE
Should raise an exception when load fails

### ISSUE THREAD

**Issue by ftsf** [define-private-public/stb_image-Nim#1]
Currently errors with an index error at
```
copyMem(pixelData[0].addr, data, pixelData.len)

read.nim(86)             load
system.nim(2581)         sysFatal
Error: unhandled exception: index out of bounds [IndexError]
```

**Comment by define-private-public** [comment]
Yeah, this sounds like a good idea.  Even though it's out of the scope of the original `stb_image` library, this makes it a little more Nim friendly.

IIRC, one would check for a `NULL` returned by the `stbi_load()` function, which is pretty trivial to do in Nim.

What would be a good name for the `Exception` class?  Could you also provide me with the minimal amount of code to reproduce the error?

**Comment by ftsf** [comment]
The c stb_image load returns nil when accessing a file that doesn't exist. your wrapper raises an index error instead before you get a chance to check the return.

Minimal code to reproduce is:

```
import stb_image.read as stbi
var w,h,components: int
var pixels = stbi.load("foo", w,h,components, stbi.Default)
```

```
Traceback (most recent call last)
test.nim(3)              test
read.nim(86)             load
system.nim(2656)         sysFatal
Error: unhandled exception: index out of bounds [IndexError]
```

I think returning an IOError would be satisfactory, but you can also return your own exception and include the stbi_failure_reason string as the message.

**Comment by define-private-public** [comment]
I tend to do development over on GitLab.  I also snuk in a version update.  Can you give this a review please:

https://gitlab.com/define-private-public/stb_image-Nim/merge_requests/1/diffs

**Comment by define-private-public** [comment]
Changes should be merged now on GitLab.  Thanks for the suggestion!
