### ISSUE TITLE
Update to stb_image_write - v1.07

### ISSUE THREAD

**Issue by Jipok** [define-private-public/stb_image-Nim#2]
There are some important changes. For example, the new version allows you to save in jpeg.
stb_image also has a newer version 2.16.

**Comment by define-private-public** [comment]
Sure thing.  I'll get on it when I get home tonight.  Thanks for the alert!

**Comment by define-private-public** [comment]
The changes don't seem like that much, but I'm a little tired today.  I'll try to get it in before the weekend is over.  Is there anything from it that's pressing you need?

**Comment by define-private-public** [comment]
Okay, this should be done.  It's up on nimble and the repo should mirror here from GitLab shortly.
