### ISSUE TITLE
Test fails: image loading (Attempt to read from nil)

### ISSUE THREAD

**Issue by mratsim** [define-private-public/stb_image-Nim#3]
I'm trying to use stb_image library but I fail to load a PNG image.

This is reproducible directly with your test suite on Nim 0.17 and devel:

```Nim
[Suite] Unit Tests for stb_image wrapper
Traceback (most recent call last)
tests.nim(60)            tests
read.nim(91)             load
read.nim(39)             failureReason
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

**Comment by define-private-public** [comment]
This seems to be an issue with the `stbi_failure_reason()` function.  Maybe I didn't bind it properly or something changed...

I'll try to have a patch up within an hour or two.

**Comment by define-private-public** [comment]
This actually seems to be something more regarding `char *` return types.  I'll spend a bit more time into this.  When I updated this last time, I sear that the tests passed.

the only thing I'm doing differently this time is that I'm using the `{.compile.}` macro to make my lifer easier.

**Comment by define-private-public** [comment]
hrmm... didn't seem to be that either.  I'm going to go escalate this to the Nim devs to see if something else is the problem.

**Comment by edubart** [comment]
I found the problem and made a PR, I've commented about the issue details on https://github.com/nim-lang/Nim/issues/6324 to maybe help others with the same problem there.

**Comment by define-private-public** [comment]
Thanks!  I'll take a look into it when I get home later today.

**Comment by define-private-public** [comment]
Okay,  I pushed the fix my GitLab repo.  It should be synced up here within the hour.  Though it should be available on nimble now.
