### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by Skaruts** [define-private-public/stb_image-Nim#6]
I'm not sure this is a problem with stb_image-nim or a problem on my end.
I'm using Nim 1.4.8 on Windows 7.

I imported the module as stated in the readme:

```nim
import stb_image/read as stbi
```

I'm not doing anything else, but I'm getting these compile errors:

```
(...)
CC: main.nim
Hint:  [Link]
C:\Users\Skaruts\nimcache\main_d\read.c.o:read.c:(.text+0x79e1): multiple definition of `stbi_failure_reason'
C:\Users\Skaruts\nimcache\main_d\textures.c.o:textures.c:(.text+0xb038): first defined here
C:\Users\Skaruts\nimcache\main_d\read.c.o:read.c:(.text+0x79e9): multiple definition of `stbi_image_free'
C:\Users\Skaruts\nimcache\main_d\textures.c.o:textures.c:(.text+0xb050): first defined here
C:\Users\Skaruts\nimcache\main_d\read.c.o:read.c:(.text+0x79f8): multiple definition of `stbi_set_flip_vertically_on_load'
C:\Users\Skaruts\nimcache\main_d\textures.c.o:textures.c:(.text+0xb05f): first defined here
C:\Users\Skaruts\nimcache\main_d\read.c.o:read.c:(.text+0x79ff): multiple definition of `stbi_load_gif_from_memory'
C:\Users\Skaruts\nimcache\main_d\textures.c.o:textures.c:(.text+0xb093): first defined here
C:\Users\Skaruts\nimcache\main_d\read.c.o:read.c:(.text+0x7af4): multiple definition of `stbi_is_hdr_from_memory'

(... a whole bunch more of those)

collect2.exe: error: ld returned 1 exit status
Error: execution of an external program failed: 'gcc.exe   -o (...)
```

**Comment by define-private-public** [comment]
Hi.

I'll take a look at this soon.  What exactly is "textures"?"  It looks like an issue where the function names have been defined twice (once by "textures" another by this library).  And that's what's causing the issue.

**Comment by Skaruts** [comment]
> What exactly is "textures"?"

I'm glad you asked that, because I hadn't realized that file isn't part of stb_image.  I'm using [nimraylib_now](https://github.com/greenfork/nimraylib_now), so it's probably raylib's textures file. I hadn't noticed this before, but Raylib itself uses stb_image, so me using both is probably causing a conflict. 

I was trying to use stb_image because raylib doesn't load jpgs by default (it requires a flag). So maybe I'll be able to sort that out without using stb_image directly.

**Comment by define-private-public** [comment]
Okay.  I don't think is an issue with my library then.  Looking at the source of nimraylib_now, they included their own copy/binding of stb_image, so I think that's where/why the conflict arises.  If that library can load images, I'd suggest using it over mine instead.

Are you fine with me closing this issue?

---

This might be something to ask the Nim folks what should happen if two Nim libraries have the same C-implemented functions included.  AFAIK, it seems like you're the first one to run into this.  But I know that stb_image is a pretty popular library, so I wouldn't be surprised if will start the happen for others down the road (and with other libraries).

**Comment by Skaruts** [comment]
Yea, this issue is pretty much resolved here, I'd say. :)

Thank you. 
Cheers.
